wiki_app/config/routes.rb
Rails.application.routes.draw do
  resources :wiki_posts
  namespace :wiki_posts do
    get 'example'
  end
  namespace :welcome do
    get 'index'
    get 'about'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check
  get 'welcome/about'
  get '/about', to: redirect('/welcome/about')
  root "welcome#index"

  # Defines the root path route ("/")
  # root "posts#index"
end

wiki_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

wiki_app/app/models/wiki_post.rb
class WikiPost < ApplicationRecord
    has_one_attached :image
    scope :contributors, -> { pluck(:author).uniq }
end

wiki_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

wiki_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
    @wiki_posts = WikiPost.all
  end
end

wiki_app/app/controllers/wiki_posts_controller.rb
class WikiPostsController < ApplicationController
  before_action :set_wiki_post, only: %i[ show edit update destroy ]

  # GET /wiki_posts or /wiki_posts.json
  def index
    @wiki_posts = WikiPost.all
  end

  # GET /wiki_posts/1 or /wiki_posts/1.json
  def show
  end

  def example
  end

  # GET /wiki_posts/new
  def new
    @wiki_post = WikiPost.new
  end

  # GET /wiki_posts/1/edit
  def edit
  end

  # POST /wiki_posts or /wiki_posts.json
  def create
    @wiki_post = WikiPost.new(wiki_post_params)

    respond_to do |format|
      if @wiki_post.save
        format.html { redirect_to wiki_post_url(@wiki_post), notice: "Wiki post was successfully created." }
        format.json { render :show, status: :created, location: @wiki_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wiki_posts/1 or /wiki_posts/1.json
  def update
    respond_to do |format|
      if @wiki_post.update(wiki_post_params)
        format.html { redirect_to wiki_post_url(@wiki_post), notice: "Wiki post was successfully updated." }
        format.json { render :show, status: :ok, location: @wiki_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wiki_posts/1 or /wiki_posts/1.json
  def destroy
    @wiki_post.destroy!

    respond_to do |format|
      format.html { redirect_to wiki_posts_url, notice: "Wiki post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki_post
      @wiki_post = WikiPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wiki_post_params
      params.fetch(:wiki_post, {}).permit(:title, :description, :author, :image)
    end
end

wiki_app/app/helpers/application_helper.rb
module ApplicationHelper
end

wiki_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

wiki_app/app/helpers/wiki_posts_helper.rb
module WikiPostsHelper
end

wiki_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= javascript_importmap_tags %>
  <%= turbo_include_tags %>
  <head>
    <title>WikiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

wiki_app/app/views/welcome/about.html.erb
<h1>Wiki</h1>
<h2>Site contributors: </h2>
<ul>
    <% @wiki_posts.contributors.compact.each do |contributor| %>
        <li><%= contributor.titleize %></li>
    <% end %>
</ul>

wiki_app/app/views/welcome/index.html.erb
<h1>My Wiki</h1>
<h2><%= link_to 'View Posts', wiki_posts_path %></h2>
<h2><%= link_to 'About', welcome_about_path %></h2>

wiki_app/app/views/wiki_posts/_form.html.erb
<%= form_with(model: wiki_post) do |form| %>
  <% if wiki_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wiki_post.errors.count, "error") %> prohibited this wiki_post from being saved:</h2>

      <ul>
        <% wiki_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

wiki_app/app/views/wiki_posts/_wiki_post.html.erb
<div id="<%= dom_id wiki_post %>">
</div>

wiki_app/app/views/wiki_posts/edit.html.erb
<h1>Edit wiki post</h1>
<%= form_with model: @wiki_post, local: true do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.submit "Update" %>
  </div>
<% end %>
<br>
<div>
  <%= link_to "Back to wiki posts", wiki_posts_path %>
</div>
<%= button_to "Destory this wiki post" @wiki_post, method: :delete %>

wiki_app/app/views/wiki_posts/example.html.erb
<h1>Welcome</h1>

wiki_app/app/views/wiki_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wiki posts</h1>

<div id="wiki_posts">
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Created at</th>
        <th>Updated at</th>
        <th>Author</th>
      </tr>
    </thead>
    <tbody>
      <% @wiki_posts.each do |post|%>
        <tr>
          <td><%= link_to post.title, wiki_post_path(post) %></td>
          <td><%= post.created_at.strftime('%B %d, %Y') %></td>
          <td><%= post.updated_at.strftime('%B %d, %Y') %></td>
          <td><%= post.author.titleize %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New wiki post", new_wiki_post_path %>

wiki_app/app/views/wiki_posts/new.html.erb
<h1>New wiki post</h1>
<%= form_with model: @wiki_post, local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :description %>
    <%= form.text_field :description %>
    <%= form.label :author %>
    <%= form.text_field :author %>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.submit "Create" %>
  </div>
<% end %>
<br>
<div>
  <%= link_to "Back to wiki posts", wiki_posts_path %>
</div>

wiki_app/app/views/wiki_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wiki_post %>

<h1><%= @wiki_post.title.titleize %></h1>
<% if @wiki_post.image.attached? %>
<%= image_tag @wiki_post.image %>
<% end %>
<p><%= @wiki_post.description %></p>
<p>Author: <%= @wiki_post.author.titleize %></p>
<p>Created on <%= @wiki_post.created_at.strftime('%B %d, %Y') %></p>
<div>
  <%= link_to "Edit this wiki post", edit_wiki_post_path(@wiki_post) %> |
  <%= link_to "Back to wiki posts", wiki_posts_path %>

  <%= button_to "Destroy this wiki post", @wiki_post, method: :delete, form: {data: {turbo_confirm: "Are you sure you want to delete this #{@wiki_post.title} ?"}} %>
</div>